import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Main, { MainProps } from '../components/main';
import { getPlatforms } from '../igdb';
import { Platform } from '../interfaces/Platform';
import styles from '../styles/Home.module.css';

const Home: NextPage<{ platforms: Platform[] }> = ({ platforms }) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Main platforms={platforms} />
			</main>

			<footer className={styles.footer}>
				<a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export const getServerSideProps: GetServerSideProps<MainProps> = async ({ req, res }) => {
	res.setHeader('Cache-Control', 'public, s-maxage=10, stale-while-revalidate=59');

	const platforms = await getPlatforms();
	return {
		props: {
			platforms,
		},
	};
};

export default Home;
